#!/usr/bin/env bash
# Build ShoryuMux.app (menu-bar) from the SwiftPM sources and assemble a bundle.
set -euo pipefail

PROJ="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_DIR="$PROJ/app"
OUT="$PROJ/build"
APP="$OUT/ShoryuMux.app"

echo "==> Injecting project path into BuildConfig.swift"
cat > "$APP_DIR/Sources/ShoryuMuxApp/BuildConfig.swift" <<EOF
import Foundation

// Generated by scripts/build-app.sh
enum BuildConfig {
    static let projectPath = "$PROJ"
}
EOF

echo "==> swift build (release)"
( cd "$APP_DIR" && swift build -c release )

BIN="$( cd "$APP_DIR" && swift build -c release --show-bin-path )/ShoryuMuxApp"
if [ ! -f "$BIN" ]; then echo "binary not found: $BIN"; exit 1; fi

echo "==> Assembling $APP"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$BIN" "$APP/Contents/MacOS/ShoryuMux"

cat > "$APP/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key><string>ShoryuMux</string>
    <key>CFBundleDisplayName</key><string>ShoryuMux</string>
    <key>CFBundleIdentifier</key><string>com.shoryumux.app</string>
    <key>CFBundleVersion</key><string>1.0</string>
    <key>CFBundleShortVersionString</key><string>1.0</string>
    <key>CFBundleExecutable</key><string>ShoryuMux</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>LSMinimumSystemVersion</key><string>13.0</string>
    <key>LSUIElement</key><true/>
    <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
EOF

echo "==> Ad-hoc code signing"
codesign --force --deep --sign - "$APP" 2>/dev/null || echo "   (codesign skipped/failed — app still runnable)"

echo "Built: $APP"
echo "Run with:  open \"$APP\""
